[theme]
primaryColor = "#2563EB"           # Bright blue for buttons/links
backgroundColor = "#0F172A"        # Deep navy background
secondaryBackgroundColor = "#1E293B" 
textColor = "#F8FAFC"              # Almost white text
font = "sans serif"
