[theme]
primaryColor="#0A192F"             # Dark Navy Blue
backgroundColor="#0F172A"          # Dark Background
secondaryBackgroundColor="#1E293B" # Slightly lighter sections
textColor="#E2E8F0"                # Light Gray Text
font="sans serif"
